OLF knitro solver extension
powsybl/powsybl-open-loadflow-knitro-solver pull request #1
Opened 2024-11-29 13:29 UTC by jeanneArchambault

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**
<Adding the knitro solver extension for the inner loop formulation of the load flow problem -->

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-11-29 18:52 UTC, jeandemanged requested changes
thanks, looks good.
After granting myself the permission (...) I did some cleanup. Don't hesistate to revert my changes if not ok.
Remains to do:
- README to be filled explaining purpose and usage (look at other powsybl repositories for examples, eg OLF README). A knitro installation guide also would be welcome there.
- CI with Knitro installation
- sonar setup in CI

2024-11-29 18:52 UTC, jeandemanged commented on src/test/java/com/powsybl/openloadflow/knitro/solver/AcLoadFlowWithCachingTest.java
either enable or delete

2024-12-02 10:14 UTC, p-arvy reviewed
Just minor comments.
Great job, @jeanneArchambault! 
And thanks for your work, @jeandemanged, especially on the CI.

2024-12-02 10:14 UTC, p-arvy commented on src/test/java/com/powsybl/openloadflow/knitro/solver/AcLoadFlow3wtTest.java
> +package com.powsybl.openloadflow.knitro.solver; /**
There seems to be a formatting error with the copyrights of all the tests.

2024-12-02 10:14 UTC, p-arvy commented on src/main/java/com/powsybl/openloadflow/knitro/solver/KnitroSolverParameters.java
> +//    public KnitroSolverParameters() {
Please update or delete these commented lines

2024-12-02 10:14 UTC, p-arvy commented on src/main/java-templates/com/powsybl/openloadflow/knitro/util/PowsyblOpenLoadFlowKnitroSolverVersion.java
> + * @author Damien Jeandemange {@literal <damien.jeandemange at rte-france.com>}
@jeandemanged did you join a new organization without letting us know? :)

2024-12-02 10:14 UTC, p-arvy commented on src/main/java/com/powsybl/openloadflow/knitro/solver/KnitroSolver.java
> +    // Handle setting lower and upper variables bounds
A Javadoc would be more appropriate here (same with the other classes in the file).

2024-12-02 10:14 UTC, p-arvy commented on src/main/java/com/powsybl/openloadflow/knitro/solver/KnitroSolver.java
> +            //                for (int var = 0; var < sortedVariables.size(); var++) { //TODO
Do you plan to handle this in this PR? 
If so, please update these commented lines.
Otherwise, please delete them, and you can indicate in an issue (or alternatively, with a TODO) what should be done later.

2024-12-02 10:14 UTC, p-arvy commented on src/main/java/com/powsybl/openloadflow/knitro/solver/KnitroSolver.java
> +//            // update network state variable //TODO later?
Do you plan to handle this in this PR? 
If so, please update these commented lines.
Otherwise, please delete them, and you can indicate in an issue (or alternatively, with a TODO) what should be done later.

2024-12-02 10:14 UTC, p-arvy commented on src/main/java/com/powsybl/openloadflow/knitro/solver/NonLinearExternalSolverUtils.java
> +    public static List<AcEquationType> getLinearConstraintsTypes() {
The method `getLinearConstraintsTypes` seems never used. Do you really need it ?
(same with `getNonLinearConstraintsTypes`)

2024-12-02 10:14 UTC, p-arvy commented on src/main/java/com/powsybl/openloadflow/knitro/solver/KnitroSolverFactory.java
> +        return new DefaultKnitroSolverStoppingCriteria(Math.pow(10, -6)); //TODO
Do you plan to handle this in this PR?
If so, please update the code.
Otherwise, please indicate in an issue (or alternatively, with a TODO) what should be done later.

2024-12-03 10:25 UTC, jeandemanged commented on src/main/java-templates/com/powsybl/openloadflow/knitro/util/PowsyblOpenLoadFlowKnitroSolverVersion.java
> + * @author Damien Jeandemange {@literal <damien.jeandemange at rte-france.com>}
oops sorry, happens occasionally when I time travel ... fixed

2024-12-13 17:25 UTC, jeandemanged approved these changes

2024-12-16 09:34 UTC, merged

2024-12-16 09:51 UTC, p-arvy approved these changes
Great job, thank you @jeanneArchambault @jeandemanged !